### YamlMime:ModuleUnit
uid: learn-bizapps.urs-customize-the-schedule-board.4-configure-schedule-board-filter-queries
title: Configure schedule board filter queries
metadata:
  title: Configure schedule board filter queries
  description: Configure schedule board filter queries
  ms.date: 1/11/2019
  author: dbeasley
  ms.author: dbeasley
  ms.topic: interactive-tutorial
  ms.prod: learning-d365
  ROBOTS: NOINDEX
durationInMinutes: 5
content: |
  [!include[](includes/4-configure-schedule-board-filter-queries.md)]
