### YamlMime:ModuleUnit 
uid: learn-bizapps.share-buttons.6-security 
title: Understand button flow connection security
metadata: 
  title: Understand button flow connection security 
  description: Learn about button flow connection security.  
  ms.date: 2/7/2020 
  author: KevSch 
  ms.author: kschimke 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-automate 
durationInMinutes: 3 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/6-security.md)] 
