### YamlMime:ModuleUnit 
uid: learn-bizapps.patient-access-service-center.2-configure-patient-access-portal 
title: Exercise - Configure and navigate the Patient Access portal
metadata: 
  title: Exercise - Configure and navigate the Patient Access portal
  description: Configure and modify an external Healthcare Portal template and create patient registration accounts. 
  ms.date: 11/30/2021 
  author: DaveBeasley 
  ms.author: dbeasley 
  ms.topic: interactive-tutorial 
  ms.prod: mscloud-healthcare 
durationInMinutes: 13 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/2-configure-patient-access-portal.md)] 
