### YamlMime:ModuleUnit 
uid: learn-bizapps.patient-access-service-center.3-configure-agent-scripts 
title: Exercise - Create and set up agent scripts
metadata: 
  title: Exercise - Create and set up agent scripts
  description: Create and set up an agent script to appear in the Productivity pane in Patient Service Center.
  ms.date: 01/21/2022 
  author: DaveBeasley 
  ms.author: dbeasley 
  ms.topic: interactive-tutorial 
  ms.prod: learning-healthcare 
durationInMinutes: 10
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/3-configure-agent-scripts.md)] 
