### YamlMime:ModuleUnit 
uid: learn-bizapps.patient-access-service-center.4-configure-knowledge-articles 
title: Exercise - Configure knowledge articles
metadata: 
  title: Exercise - Configure knowledge articles
  description: Learn how to create and manage knowledge articles in the Patient Service Center.
  ms.date: 11/30/2021 
  author: DaveBeasley 
  ms.author: dbeasley 
  ms.topic: interactive-tutorial 
  ms.prod: mscloud-healthcare 
durationInMinutes: 13 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/4-configure-knowledge-articles.md)] 
