### YamlMime:ModuleUnit 
uid: learn-bizapps.modern-analytics-excel.3-types-security 
title: Dataset types and security
metadata: 
  title: Dataset types and security
  description: Learn about dataset types and security.
  ms.date: 09/28/2021 
  author: heyrob 
  ms.author: robde 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-bi 
durationInMinutes: 5 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/3-types-security.md)] 
