### YamlMime:ModuleUnit
uid: learn-bizapps.urs-customize-the-schedule-board.4-configure-schedule-board-filter-queries
title: Configure schedule board filter queries
metadata:
  title: Configure schedule board filter queries
  description: Configure schedule board filter queries
  ms.date: 02/01/2019
  author: DaveBeasley
  ms.author: dbeasley
  ms.topic: interactive-tutorial
  ms.prod: learning-d365-field-service
  ROBOTS: NOINDEX
durationInMinutes: 5
content: |
  [!include[](../includes/banner.md)]
  [!include[](includes/4-configure-schedule-board-filter-queries.md)]

