### YamlMime:ModuleUnit
uid: learn-bizapps.wwl.introduction-common-data-service.environments-common-data-service
title: Environments in Common Data Service
metadata:
  title: Environments in Common Data Service
  description: Environments in Common Data Service
  ms.date: 12/20/2019
  author: wwlpublish
  ms.author: styang
  ms.topic: interactive-tutorial
  ms.prod: learning-power-apps
azureSandbox: false
durationInMinutes: 3
content: |
  [!include[](includes/5-environments.md)]