### YamlMime:ModuleUnit
uid: learn-bizapps.wwl.introduction-common-data-service.environments-common-data-service
title: Environments in Microsoft Dataverse
metadata:
  title: Environments in Dataverse
  description: "Environments in Dataverse"
  ms.date: 09/24/2020
  author: wwlpublish
  ms.author: skulthm
  ms.topic: interactive-tutorial
  ms.prod: learning-power-apps
azureSandbox: false
durationInMinutes: 3
content: |
  [!include[](includes/5-environments.md)]
