### YamlMime:ModuleUnit 
uid: learn-bizapps.get-started-with-ai-builder-text-recognition.4-build-application 
title: Build a Power Apps application that uses AI Builder Text recognition
metadata: 
  title: Build a Power Apps application that uses AI Builder Text recognition
  description: Learn how to build a Power Apps application that uses AI Builder Text recognition.
  ms.date: 04/10/2020 
  author: heyrob 
  ms.author: robde 
  ms.topic: interactive-tutorial 
  ms.prod: learning-d365-ai-builder 
durationInMinutes: 15
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/4-build-application.md)] 
