### YamlMime:ModuleUnit
uid: learn-bizapps.powerapps-manage.3-powerapps-environments
title: Understand environments in PowerApps
metadata:
  title: Understand environments in PowerApps
  description: Learn how to work with environments in PowerApps.
  ms.date: 5/21/2019
  author: kevsch
  ms.author: kevsch
  ms.topic: interactive-tutorial
  ms.prod: learning-powerapps
durationInMinutes: 12
content: |
  [!include[](includes/3-powerapps-environments.md)]
