### YamlMime:ModuleUnit
uid: learn-bizapps.powerapps-manage.3-powerapps-environments
title: Exercise - Understand environments in Power Apps
metadata:
  title: Exercise - Understand environments in Power Apps
  description: Learn how to work with environments in Power Apps.
  ms.date: 06/01/2021
  author: DaveBeasley
  ms.author: dbeasley
  ms.topic: interactive-tutorial
  ms.prod: learning-powerapps
durationInMinutes: 12
content: |
  [!include[](../includes/unit-banner.md)]
  [!include[](includes/3-powerapps-environments.md)]

