### YamlMime:ModuleUnit 
uid: learn-bizapps.plan-manage-environment.5-plan-environment 
title: Plan environments and variance
metadata: 
  title: Plan environments and variance 
  description: Learn about planning environments and variance.  
  ms.date: 2/29/2020 
  author: KevSch 
  ms.author: kschimke 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-automate 
durationInMinutes: 5 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/5-plan-environment.md)] 
