### YamlMime:ModuleUnit
uid: learn-bizapps.using-iot-central-with-connected-field-service.2-create-an-iot-central-application
title: Create an IoT Central Application
metadata:
  title: Create an IoT Central Application
  description: Create an IoT Central Application
  ms.date: 02/01/2019
  author: dyack
  ms.author: dbeasley
  ms.topic: interactive-tutorial
  ms.prod: learning-d365
durationInMinutes: 15
content: |
  [!include[](../includes/unit-banner.md)]
  [!include[](includes/2-create-an-iot-central-application.md)]

