### YamlMime:ModuleUnit
uid: learn-bizapps.using-IoT-central-with-connected-field-service.2-create-an-IoT-central-application
title: Create an IoT Central Application
metadata:
  title: Create an IoT Central Application
  description: Create an IoT Central Application
  ms.date: 09/24/2018
  #TODO: Update with real author name.
  author: amsilb
  ms.author: amsilb
  ms.topic: interactive-tutorial
  ms.prod: learning-d365
durationInMinutes: 5
content: |
  [!include[](includes/2-create-an-IoT-central-application.md)]
