### YamlMime:ModuleUnit 
uid: learn-bizapps.import-export-solutions.environment-variable-basics 
title: Environment variables 
metadata: 
  title: Environment variables 
  description: Learn about environment variables.
  ms.date: 03/11/2022 
  author: jadaphillips 
  ms.author: jadaphillips 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-automate 
durationInMinutes: 5 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/environment-variable-basics.md)] 
