### YamlMime:ModuleUnit 
uid: learn-bizapps.healthcare-care-management.3-navigate-application 
title: Exercise - Navigate the Care Management application
metadata: 
  title: Exercise - Navigate the Care Management application
  description: Learn how to navigate the Care Management application.
  ms.date: 01/21/2022 
  author: DaveBeasley 
  ms.author: dbeasley 
  ms.topic: interactive-tutorial 
  ms.prod: learning-industry-solutions 
durationInMinutes: 5 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/3-navigate-application.md)] 
