### YamlMime:ModuleUnit
uid: learn-bizapps.implement-get-started-with-microsoft-dynamics-365-for-field-service-mobile.1-field-service-mobile-application-overview
title: Overview of Field Service Mobile
metadata:
  title: Overview of Field Service Mobile 
  description: A high-level overview of Field Service Mobile  
  ms.date: 01/25/2019
  author: DaveBeasley
  ms.author: dbeasley
  ms.topic: interactive-tutorial
  ms.prod: learning-d365-field-service
  ROBOTS: NOINDEX
durationInMinutes: 9
content: |
  [!include[](includes/1-field-service-mobile-application-overview.md)]
