### YamlMime:ModuleUnit
uid: learn-bizapps.implement-get-started-with-microsoft-dynamics-365-for-field-service-mobile.2-deploy-and-customize-the-mobile-application
title: Deploy and customize Field Service Mobile
metadata:
  title: Deploy and customize Field Service Mobile
  description: Deploy and customize Field Service Mobile 
  ms.date: 01/25/2019
  author: DaveBeasley
  ms.author: dbeasley
  ms.topic: interactive-tutorial
  ms.prod: learning-d365-field-service
  ROBOTS: NOINDEX
durationInMinutes: 8
content: |
  [!include[](includes/2-deploy-and-customize-the-mobile-application.md)]
