### YamlMime:ModuleUnit
uid: learn-bizapps.implement-get-started-with-microsoft-dynamics-365-for-field-service-mobile.3-install-and-configure-the-mobile-application-client
title: Install and configure the Field Service Mobile client 
metadata:
  title: Install and configure the Field Service Mobile client 
  description: Install and configure the Field Service Mobile client 
  ms.date: 01/25/2019
  author: DaveBeasley
  ms.author: dbeasley
  ms.topic: interactive-tutorial
  ms.prod: learning-d365-field-service
  ROBOTS: NOINDEX
durationInMinutes: 10
content: |
  [!include[](../includes/unit-banner.md)]
  [!include[](includes/3-install-and-configure-the-mobile-application-client.md)]

