### YamlMime:ModuleUnit
uid: learn-bizapps.implement-get-started-with-microsoft-dynamics-365-for-field-service-mobile.6-deploy-and-configure-mobile-application-projects
title: Exercise - Deploy and configure Field Service Mobile projects 
metadata:
  title: Exercise - Deploy and configure Field Service Mobile projects  
  description: Exercise - Deploy and configure Field Service Mobile projects  
  ms.date: 01/25/2019
  author: DaveBeasley
  ms.author: dbeasley
  ms.topic: interactive-tutorial
  ms.prod: learning-d365-field-service
  ROBOTS: NOINDEX
durationInMinutes: 20
content: |
  [!include[](../includes/banner.md)]
  [!include[](includes/6-deploy-and-configure-mobile-application-projects.md)]

