### YamlMime:ModuleUnit 
uid: learn-bizapps.process-properties.2-configure-process-security-settings 
title: Configure process security
metadata: 
  title: Configure process security
  description: Configure security in process properties
  ms.date: 08/07/2020 
  author: georgiostrantzas 
  ms.author: getrantz 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-automate
durationInMinutes: 5 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/2-configure-process-security-settings.md)] 
