### YamlMime:ModuleUnit 
uid: learn-bizapps.process-properties.5-configure-level-three-error-handling 
title: Configure the third level of error handling
metadata: 
  title: Configure the third level of error handling
  description: Configure the third level of error handling
  ms.date: 08/07/2020 
  author: georgiostrantzas 
  ms.author: getrantz 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-automate 
durationInMinutes: 7 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/5-configure-level-three-error-handling.md)] 
