### YamlMime:ModuleUnit
uid: learn-bizapps.powerapps.discover-web-apis-power-apps.04-what-is-openapi-and-why-you-should-use-it
title: What is OpenAPI and why you should use it
metadata:
  title: What is OpenAPI and why you should use it
  description: Learn what the OpenAPI spec is and why we should use it for custom connectors
  ms.date: 04/16/2021
  author: justinyoo
  ms.author: juyoo
  ms.topic: interactive-tutorial
  ms.prod: learning-powerapps
durationInMinutes: 5
content: | 
  [!include[](includes/04-what-is-openapi-and-why-you-should-use-it.md)]