### YamlMime:ModuleUnit
uid: learn-bizapps.virtual-visits.2-configure-app
title: Configure Virtual Clinic application
metadata:
  title: Configure Virtual Clinic application
  description: Learn to configure the Microsoft Cloud for Healthcare Virtual Clinic application.
  ms.date: 11/05/2021
  author: DaveBeasley
  ms.author: dbeasley
  ms.topic: interactive-tutorial
  ms.prod: learning-industry-solutions
durationInMinutes: 30
content: |
 [!include[](../includes/unit-banner.md)]
 [!include[](includes/2-configure-app.md)]
