### YamlMime:ModuleUnit
uid: learn-bizapps.virtual-visits.3-configure-teams
title: Configure Microsoft Teams for virtual visits
metadata:
  title: Configure Microsoft Teams for virtual visits
  description: Learn to configure Microsoft Teams to schedule and conduct virtual visits remotely with patients.
  ms.date: 01/21/2022
  author: DaveBeasley
  ms.author: dbeasley
  ms.topic: interactive-tutorial
  ms.prod: learning-industry-solutions
durationInMinutes: 10
content: |
 [!include[](../includes/unit-banner.md)]
 [!include[](includes/3-configure-teams.md)]
