### YamlMime:ModuleUnit 
uid: learn-bizapps.modern-analytics-intro.5-modern-analytics-applications 
title: Install and update modern analytics applications
metadata: 
  title: Install and update modern analytics applications
  description: Learn how to install and update modern analytics applications.
  ms.date: 09/13/2021 
  author: heyrob 
  ms.author: robde 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-bi 
durationInMinutes: 2 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/5-modern-analytics-applications.md)] 
