### YamlMime:ModuleUnit
uid: learn-bizapps.remotely-monitor-and-service-customer-equipment.6-Building-CFS-Processes-and-Automations
title: Building CFS Processes and Automations 
metadata:
  title: Building CFS Processes and Automations
  ms.date: 09/24/2018
  #TODO: Update with real author name.
  author: dbeasley
  ms.author: dbeasley
  ms.topic: interactive-tutorial
  ms.prod: learning-d365
durationInMinutes: 5
content: |
  [!include[](includes/6-Building-CFS-Processes-and-Automations.md)]
