### YamlMime:ModuleUnit
uid: learn-bizapps.remotely-monitor-and-service-customer-equipment.6-building-cfs-processes-and-automations
title: Building Connected Field Service processes and automations 
metadata:
  title: Building Connected Field Service processes and automations 
  description: Building Connected Field Service processes and automations 
  ms.date: 02/01/2019
  author: dyack
  ms.author: dbeasley
  ms.topic: interactive-tutorial
  ms.prod: learning-d365
durationInMinutes: 25
content: |
  [!include[](../includes/banner.md)]
  [!include[](includes/6-Building-CFS-Processes-and-Automations.md)]

