### YamlMime:ModuleUnit 
uid: learn-bizapps.unified-customer-profile.3-explore-application 
title: Exercise - Explore the Unified customer profile application
metadata: 
  title: Exercise - Explore the Unified customer profile application
  description: In this exercise, you will explore the Unified customer profile application.
  ms.date: 01/14/2022 
  author: DaveBeasley 
  ms.author: dbeasley 
  ms.topic: interactive-tutorial 
  ms.prod: learning-industry-solutions 
durationInMinutes: 6 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/3-explore-application.md)] 
