### YamlMime:ModuleUnit 
uid: learn-bizapps.winautomation-powerautomate.3-exercise-create-flow-call-winautomation 
title: Create a flow that calls a WinAutomation process
metadata: 
  title: Create a flow that calls a WinAutomation process
  description: An exercise to demonstrate how a WinAutomation process can be run from a flow.
  ms.date: 10/08/2020 
  author: olegmelnykov 
  ms.author: olmelnyk 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-automate 
durationInMinutes: 20 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/3-exercise-create-flow-call-winautomation.md)] 
