### YamlMime:ModuleUnit 
uid: learn-bizapps.intro-portals.4-portal-security 
title: Overview of portal security 
metadata: 
  title: Overview of portal security  
  description: Overview of portal security  
  ms.date: 6/30/2020 
  author: DaveBeasley 
  ms.author: dbeasley 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-apps-portals 
durationInMinutes: 5 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/4-portal-security.md)] 
