### YamlMime:ModuleUnit 
uid: learn-bizapps.return-school.4-configuration 
title: Configuration steps
metadata: 
  title: Configuration steps 
  description: Learn about the steps to configure the Return to School solution. 
  ms.date: 04/28/2021 
  author: DaveBeasley 
  ms.author: dbeasley 
  ms.topic: interactive-tutorial 
  ms.prod: learning-d365-return-school 
durationInMinutes: 2 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/4-configuration.md)] 
