### YamlMime:ModuleUnit
uid: learn-bizapps.implement-power-virtual-agents.2-environments
title: Environments in Power Virtual Agents
metadata:
  title: Environments in Power Virtual Agents
  description: Learn how to create bots in different environments.
  ms.date: 03/09/2022
  author: heyrob
  ms.author: robde
  ms.topic: interactive-tutorial
  ms.prod: learning-power-virtual-agents
durationInMinutes: 5
content: |
 [!include[](../includes/unit-banner.md)]
 [!include[](includes/2-environments.md)]
