### YamlMime:ModuleUnit 
uid: learn-bizapps.azure-health-bot.3-configure-customer-service-ominchannel-chat 
title: Configure Customer Service Omnichannel Live Channel
metadata: 
  title: Configure Customer Service Omnichannel Live Channel
  description: Configure live chat for Dynamics 365 Omnichannel for Customer Service to connect and engage with their customers across digital messaging channels.
  ms.date: 11/10/2021 
  author: dbeasley 
  ms.author: davebeasley 
  ms.topic: interactive-tutorial 
  ms.prod: learning-industry-solutions 
durationInMinutes: 5 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/3-configure-customer-service-ominchannel-chat.md)] 
