### YamlMime:ModuleUnit
uid: learn-bizapps.azure-health-bot.3-configure-customer-service-omnichannel-chat
title: Configure Customer Service Omnichannel live chat
metadata:
  title: Configure Customer Service Omnichannel live chat
  description: Configure live chat for Dynamics 365 Omnichannel for Customer Service to connect and engage with their customers across digital messaging channels.
  ms.date: 01/21/2022
  author: DaveBeasley
  ms.author: dbeasley
  ms.topic: interactive-tutorial
  ms.prod: learning-industry-solutions
durationInMinutes: 10
content: |
 [!include[](../includes/unit-banner.md)]
 [!include[](includes/3-configure-customer-service-omnichannel-chat.md)]
