### YamlMime:ModuleUnit 
uid: learn-bizapps.winautomation-power-automate.3-exercise-create-flow-call-winautomation 
title: Exercise - Create a flow that calls a WinAutomation process
metadata: 
  title: Exercise - Create a flow that calls a WinAutomation process
  description: Follow this exercise to practice running a WinAutomation process can be run from a flow.
  ms.date: 08/24/2020 
  author: mariosleon 
  ms.author: marleon 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-automate 
durationInMinutes: 20 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/3-exercise-create-flow-call-winautomation.md)] 
