### YamlMime:ModuleUnit 
uid: learn-bizapps.configure-custom-connectors-api.6-environments 
title: Share and move between environments
metadata: 
  title: Share and move between environments 
  description: Learn how to share and move between environments. 
  ms.date: 03/11/2021 
  author: DaveBeasley 
  ms.author: dbeasley 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-platform 
durationInMinutes: 3
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/6-environments.md)] 
