### YamlMime:ModuleUnit 
uid: learn-bizapps.get-started-advanced-configuration.1-accessing-advanced-settings 
title: Accessing advanced settings
metadata: 
  title: Accessing advanced settings 
  description: Accessing advanced settings 
  ms.date: 1/23/2019 
  author: DaveBeasley
  ms.author: dbeasley 
  ms.topic: interactive-tutorial 
  ms.prod: learning-d365 
  ROBOTS: NOINDEX 
durationInMinutes: 5 
content: |
  [!include[](../includes/unit-banner.md)]
  [!include[](includes/1-accessing-advanced-settings.md)] 

