### YamlMime:ModuleUnit 
uid: learn-bizapps.get-started-advanced-configuration.3-configuring-business-management 
title: Configuring business management settings
metadata: 
  title: Configuring business management settings 
  description: Configuring business management settings 
  ms.date: 1/23/2019 
  author: DaveBeasley
  ms.author: dbeasley 
  ms.topic: interactive-tutorial 
  ms.prod: learning-d365 
  ROBOTS: NOINDEX 
durationInMinutes: 5 
content: | 
 [!include[](includes/3-configuring-business-management.md)] 
