### YamlMime:ModuleUnit 
uid: learn-bizapps.get-started-advanced-configuration.4-configuring-marketing-settings 
title: Configuring marketing settings 
metadata: 
  title: Configuring marketing settings  
  description: Configuring marketing settings  
  ms.date: 1/23/2019 
  author: DaveBeasley
  ms.author: dbeasley 
  ms.topic: interactive-tutorial 
  ms.prod: learning-d365 
  ROBOTS: NOINDEX 
durationInMinutes: 5 
content: | 
 [!include[](includes/4-configuring-marketing-settings.md)] 
