### YamlMime:ModuleUnit 
uid: learn-bizapps.get-started-advanced-configuration.5-configuring-event-management-settings 
title: Configuring event management settings
metadata: 
  title: Configuring event management settings 
  description: Configuring event management settings 
  ms.date: 1/23/2019 
  author: DaveBeasley
  ms.author: dbeasley 
  ms.topic: interactive-tutorial 
  ms.prod: learning-d365 
  ROBOTS: NOINDEX 
durationInMinutes: 5 
content: |
  [!include[](../includes/unit-banner.md)]
  [!include[](includes/5-configuring-event-management-settings.md)] 

