### YamlMime:ModuleUnit 
uid: learn-bizapps.automating-email-handling.1-introducing-email-automation 
title: Introduction
metadata: 
  title: Introduction
  description: Introduction to email handling with WinAutomation
  ms.date: 09/21/2020 
  author: mariosleon 
  ms.author: marleon 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-automate 
durationInMinutes: 2 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/1-introducing-email-automation.md)] 
