### YamlMime:ModuleUnit 
uid: learn-bizapps.instrumentation-app-insights.2-configure 
title: Configure a Power Apps for Azure Application Insights
metadata: 
  title: Configure a Power Apps for Azure Application Insights
  description: Learn how to configure a Power Apps for Azure Application Insights.
  ms.date: 11/12/2021 
  author: jadaphillips 
  ms.author: jadaphillips 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-apps 
durationInMinutes: 4 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/2-configure.md)] 
