### YamlMime:ModuleUnit 
uid: learn-bizapps.build-first-desktop-flow.2-set-up-environment 
title: Set up the environment
metadata: 
  title: Set up the environment 
  description: Learn how to set up the environment. 
  ms.date: 03/31/2021 
  author: DaveBeasley 
  ms.author: dbeasley 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-automate 
durationInMinutes: 3 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/2-set-up-environment.md)] 
