### YamlMime:ModuleUnit
uid: learn-bizapps.powerapps.discover-webapis-powerapps.04-what-is-openapi-and-why-should-use-it
title: What Is OpenAPI and Why Should Use It
metadata:
  title: What Is OpenAPI and Why Should Use It
  description: Learn what the OpenAPI spec is and why we should use it for custom connectors
  ms.date: 04/02/2021
  author: justinyoo
  ms.author: juyoo
  ms.topic: interactive-tutorial
  ms.prod: learning-powerapps
durationInMinutes: 3
content: | 
  [!include[](includes/04-what-is-openapi-and-why-should-use-it.md)]