### YamlMime:ModuleUnit
uid: learn-bizapps.powerapps.discover-webapis-powerapps.05-create-custom-connector-with-openapi
title: Exercise - Create a custom connector from an OpenAPI document
metadata:
  title: Exercise - Create a custom connector from an OpenAPI document
  description: Create a custom connector directly from the OpenAPI document
  ms.date: 04/12/2021
  author: justinyoo
  ms.author: juyoo
  ms.topic: interactive-tutorial
  ms.prod: learning-powerapps
durationInMinutes: 3
content: | 
  [!include[](includes/05-create-custom-connector-with-openapi.md)]