### YamlMime:ModuleUnit
uid: learn-bizapps.powerapps.discover-webapis-powerapps.5-create-custom-connector-with-openapi
title: Create Custom Connector from OpenAPI Document
metadata:
  title: Create Custom Connector from OpenAPI Document
  description: Create a custom connector directly from the OpenAPI document
  ms.date: 03/05/2021
  author: justinyoo
  ms.author: juyoo
  ms.topic: interactive-tutorial
  ms.prod: learning-powerapps
durationInMinutes: 3
content: | 
  [!include[](includes/5-create-custom-connector-with-openapi.md)]