### YamlMime:ModuleUnit
uid: learn.wwl.implement-rpa-power-automate-ui-flows-ai-builder.use-ui-automation-enter-information-legacy-application
title: Build a UI flow to automate data entry into a legacy application
metadata:
  title: Build a UI flow to automate data entry into a legacy application
  description: "Build a UI flow to automate data entry into a legacy application"
  ms.date: 06/21/2020
  author: wwlpublish
  ms.author: ceperezb
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
azureSandbox: false
durationInMinutes: 6
content: |
  [!include[](includes/5-use-ui-automation-enter-information-legacy-application.md)]