### YamlMime:ModuleUnit 
uid: learn-bizapps.intro-to-power-bi-mobile-apps.6-configure-app-settings
title: Configure app settings
metadata: 
  title:  Configure app settings
  description: Learn how to configure your app for increased security and ease of use. 
  ms.date: 11/26/2021 
  author: paulinbar
  ms.author: painbar 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-bi 
   
durationInMinutes: 12 
content: |
  [!include[](../includes/unit-banner.md)]
  [!include[](includes/6-configure-app-settings.md)] 

