### YamlMime:ModuleUnit
uid: learn-bizapps.financial-services-customer-intelligence.4-configure-churn-model
title: Set up the Retail banking churn model in Customer Insights
metadata:
  title: Set up the Retail banking churn model in Customer Insights
  description: Learn how to set up the Retail banking churn model in Dynamics 365 Customer Insights.
  ms.date: 01/21/2022
  author: DaveBeasley
  ms.author: dbeasley
  ms.topic: interactive-tutorial
  ms.prod: learning-mscloud-financial
durationInMinutes: 6
content: |
 [!include[](../includes/unit-banner.md)]
 [!include[](includes/4-configure-churn-model.md)]
