### YamlMime:ModuleUnit
uid: learn-bizapps.financial-services-customer-intelligence.4-configure-churn-model
title: Configure the Retail Banking churn model in Dynamics 365 Customer Insights
metadata:
  title: Configure the Retail Banking churn model in Dynamics 365 Customer Insights
  description: Learn to configure the Retail Banking churn model in Dynamics 365 Customer Insights.
  ms.date: 01/28/2022
  author: DaveBeasley
  ms.author: dbeasley
  ms.topic: interactive-tutorial
  ms.prod: learning-mscloud-financial
durationInMinutes: 6
content: |
 [!include[](../includes/unit-banner.md)]
 [!include[](includes/4-configure-churn-model.md)]
