### YamlMime:ModuleUnit 
uid: learn-bizapps.modern-analytics-publish-share.2-security 
title: Row-level security
metadata: 
  title: Row-level security
  description: Learn about row-level security.
  ms.date: 09/28/2021 
  author: heyrob 
  ms.author: robde 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-bi 
durationInMinutes: 10 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/2-security.md)] 
