### YamlMime:ModuleUnit 
uid: learn-bizapps.deployment-planning-healthcare.2-healthcare-powered-deployment-planning 
title: Healthcare powered by Dynamics 365 deployment planning 
metadata: 
  title: Healthcare powered by Dynamics 365 deployment planning  
  description: Learn about Healthcare powered by Dynamics 365 deployment planning. 
  ms.date: 02/08/2021 
  author: DaveBeasley 
  ms.author: dbeasley 
  ms.topic: interactive-tutorial 
  ms.prod: learning-d365-healthcare 
durationInMinutes: 10 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/2-healthcare-powered-deployment-planning.md)] 
