### YamlMime:ModuleUnit 
uid: learn-bizapps.integrate-common-data-service.4-web-form-configure 
title: Configure web forms
metadata: 
  title: Configure web forms
  description: Learn to set up web form properties and steps, and to add the web form to your portal.
  ms.date: 07/08/2020 
  author: DaveBeasley 
  ms.author: dbeasley 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-apps 
durationInMinutes: 5 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/4-web-form-configure.md)] 
