### YamlMime:ModuleUnit 
uid: learn-bizapps.integrate-common-data-service.4-web-form-configure 
title: Configure web forms
metadata: 
  title: Configure web forms
  description: Learn how to set up web form properties and steps and how to add the web form to your portal.
  ms.date: 06/01/2021 
  author: DaveBeasley 
  ms.author: dbeasley 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-apps 
durationInMinutes: 10
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/4-web-form-configure.md)] 
