### YamlMime:ModuleUnit
uid: learn-bizapps.urs-configure-bookable-resources.6-setup-and-configure-bookable-resources
title: Exercise - Set up and configure bookable resources
metadata:
  title: Exercise - Set up and configure bookable resources
  description: Exercise - Set up and configure bookable resources
  ms.date: 02/01/2019
  author: DaveBeasley
  ms.author: dbeasley
  ms.topic: interactive-tutorial
  ms.prod: learning-d365-field-service
  ROBOTS: NOINDEX
durationInMinutes: 20
content: |
  [!include[](includes/6-setup-and-configure-bookable-resources.md)]
