### YamlMime:ModuleUnit
uid: learn-bizapps.implement-configure-microsoft-dynamics-365-for-field-service.1-key-field-service-configuration-considerations
title: Key Field Service configuration considerations 
metadata:
  title: Key Field Service configuration considerations 
  description: Key Field Service configuration considerations 
  ms.date: 01/25/2019
  author: DaveBeasley
  ms.author: dbeasley
  ms.topic: interactive-tutorial
  ms.prod: learning-d365-field-service
  ROBOTS: NOINDEX
durationInMinutes: 5
content: |
  [!include[](includes/1-key-field-service-configuration-considerations.md)]
