### YamlMime:ModuleUnit
uid: learn-bizapps.implement-configure-microsoft-dynamics-365-for-field-service.6-configuring-field-service-settings
title: Exercise - Configure Field Service settings
metadata:
  title: Exercise - Configure Field Service settings
  description: Exercise - Configure Field Service settings
  ms.date: 01/25/2019
  author: DaveBeasley
  ms.author: dbeasley
  ms.topic: interactive-tutorial
  ms.prod: learning-d365-field-service
  ROBOTS: NOINDEX
durationInMinutes: 25
content: |
  [!include[](../includes/unit-banner.md)]
  [!include[](includes/6-configuring-field-service-settings.md)]

