### YamlMime:ModuleUnit
uid: learn-bizapps.voc-response-routing-survey-scoring.6-configuring-client-server-response-routing-actions
title: Configure client and server response routing actions
metadata:
  title: Configure client and server response routing actions
  description: Configure client and server response routing actions
  ms.date: 02/02/2019
  author: DaveBeasley
  ms.author: dbeasley
  ms.topic: interactive-tutorial
  ms.prod: learning-d365
  ROBOTS: NOINDEX
durationInMinutes: 7
content: |
  [!include[](../includes/banner.md)]
  [!include[](includes/6-configuring-client-server-response-routing-actions.md)]

