### YamlMime:ModuleUnit 
uid: learn-bizapps.pad-power-automate.3-exercise-create-flow-call-pad
title: Exercise - Create a flow that calls a Power Automate Desktop process
metadata: 
  title: Exercise - Create a flow that calls a Power Automate Desktop process
  description: Follow this exercise to practice running a Power Automate Desktop process from a flow.
  ms.date: 12/10/2020  
  author: georgiostrantzas  
  ms.author: v-gtrantzas  
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-automate 
durationInMinutes: 20 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/3-exercise-create-flow-call-pad.md)] 
