### YamlMime:ModuleUnit
uid: learn-bizapps.application-lifecycle-management.4-configuration
title: Configuration and Reference data
metadata:
  title: Configuration and Reference data
  description: References through the release process
  ms.date: 04/01/2021
  author: DaveBeasley
  ms.author: dbeasley 
  ms.topic: interactive-tutorial
  ms.prod: learning-power-platform-solution-architect
durationInMinutes: 4
content: |
 [!include[](../includes/unit-banner.md)]
 [!include[](includes/4-configuration.md)]
