### YamlMime:ModuleUnit 
uid: learn-bizapps.powerapps-design-model-driven-apps.5b-create-a-model-driven-application
title: Exercise - Create a model-driven app 
metadata: 
  title: Exercise - Create a model-driven app 
  description: Create a model-driven app using Common Data Service data. 
  ms.date: 01/17/2020
  author: KevSch
  ms.author: kschimke
  ms.topic: interactive-tutorial
  ms.prod: learning-powerapps
durationInMinutes: 10 
content: |
  [!include[](../includes/unit-banner.md)]
  [!include[](includes/5b-create-a-model-driven-application)]