### YamlMime:ModuleUnit 
uid: learn-bizapps.powerapps-design-model-driven-apps.5b-create-model-driven-application
title: Exercise - Create a model-driven app 
metadata: 
  title: Exercise - Create a model-driven app 
  description: Create a model-driven app using Common Data Service data. 
  ms.date: 01/17/2020
  author: KevSch
  ms.author: kschimke
  ms.topic: interactive-tutorial
  ms.prod: learning-powerapps
durationInMinutes: 10 
content: |
  [!include[](../includes/unit-banner.md)]
<<<<<<< HEAD:learn-bizapps-pr/powerapps/get-started-with-model-driven-apps-in-powerapps/5b-create-model-driven-application.yml
  [!include[](includes/5b-create-model-driven-application.md)]
=======
  [!include[](includes/5b-create-a-model-driven-application.md)]
>>>>>>> 9523c3b1c2502f4b0c18a1f923256b4da9999019:learn-bizapps-pr/powerapps/get-started-with-model-driven-apps-in-powerapps/5b-create-a-model-driven-application.yml
