### YamlMime:ModuleUnit 
uid: learn-bizapps.powerapps-design-model-driven-apps.5b-create-model-driven-application
title: Exercise - Create a model-driven app 
metadata: 
  title: Exercise - Create a model-driven app 
  description: Create a model-driven app using Microsoft Dataverse data. 
  ms.date: 06/29/2021
  author: DaveBeasley
  ms.author: dbeasley
  ms.topic: interactive-tutorial
  ms.prod: learning-powerapps
durationInMinutes: 10 
content: |
  [!include[](../includes/unit-banner.md)]
  [!include[](includes/5b-create-model-driven-application.md)]
