### YamlMime:ModuleUnit
uid: learn-bizapps.security-modeling.2-environment
title: Environment security
metadata:
  title: Environment security
  description: Controlling access to environments and resources
  ms.date: 04/01/2021
  author: DaveBeasley
  ms.author: dbeasley 
  ms.topic: interactive-tutorial
  ms.prod: learning-power-platform-solution-architect
durationInMinutes: 11
content: |
 [!include[](../includes/unit-banner.md)]
 [!include[](includes/2-environment.md)]
