### YamlMime:ModuleUnit 
uid: learn-bizapps.winautomation-options.2-configure-notification-settings 
title: Configure notification settings
metadata: 
  title: Configure notification settings
  description: Learn how to configure notification settings.
  ms.date: 08/20/2020 
  author: mariosleon 
  ms.author: marleon 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-automate  
durationInMinutes: 3 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/2-configure-notification-settings.md)] 
