### YamlMime:ModuleUnit 
uid: learn-bizapps.security-governance-intro.2-environments 
title: Identify Power Platform environments
metadata: 
  title: Identify Power Platform environments 
  description: Learn how to identify Power Platform environments.  
  ms.date: 3/09/2020 
  author: KevSch 
  ms.author: kschimke 
  ms.topic: interactive-tutorial 
  ms.prod: learning-power-automate 
durationInMinutes: 5 
content: | 
 [!include[](../includes/unit-banner.md)] 
 [!include[](includes/2-environments.md)] 
